service: image-lambdas

# https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-dotenv-plugin
  - serverless-latest-layer-version
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: ap-northeast-2
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 10
  versionFunctions: false # optional, default is true
  vpc:
    securityGroupIds:
      - sg-0eaff0ab58013cc7a
    subnetIds:
      - subnet-0b7cfaafe9a77d6eb
      - subnet-0d123ce55a6c87253
  deploymentBucket:
    name: image-deploy-source
    serverSideEncryption: AES256
  deploymentPrefix: serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::gs-image'
        - 'arn:aws:s3:::gs-image/*'

custom:
  node_modules_layer: arn:aws:lambda:ap-northeast-2:501954793022:layer:image-modules-${opt:stage}:latest
  s3_bucket: gs-image

functions: ${file(./src/functions.yml)}

package:
  individually: true
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.DS_Store'
    - '!npm-debug.log'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.eslintrc'
    - '!.idea/**'
    - '!bitbucket-pipelines.yml'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - '!node_modules/**'
    - '!layers/**'
    - '!src/**'
