service: image-lambdas

# https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-dotenv-plugin
  - serverless-latest-layer-version
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: ap-northeast-2
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 10
  versionFunctions: false # optional, default is true
  vpc:
    securityGroupIds:
      - sg-072db964942e34407
    subnetIds:
      - subnet-00b9499b2e3d3640c
      - subnet-0281dcc4ee8e51d84
  deploymentBucket:
    name: serverless-deploy-source
    serverSideEncryption: AES256
  deploymentPrefix: serverless
  environment:
    LAYER_MODULES: arn:aws:lambda:ap-northeast-2:931620604955:layer:image-modules-${opt:stage}:latest

functions: ${file(./src/functions.yml)}

package:
  individually: true
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.DS_Store'
    - '!npm-debug.log'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.eslintrc'
    - '!.idea/**'
    - '!bitbucket-pipelines.yml'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - '!node_modules/**'
    - '!layer/**'
    - '!src/**'
